log_server:
  # log server address
  url: "foo.com/bar"
  # http or https
  protocal: "https"
  # whether we verify the server's TLS certificate
  verify: true
  # path to ssl client cert file (.pem)
  cert_file: ""
